# Generated by Django 5.0 on 2024-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='cliente',
            field=models.CharField(blank=True, default='Cliente', max_length=100, null=True),
        ),
    ]
