# Generated by Django 5.0.4 on 2024-06-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
