# Generated by Django 5.0.4 on 2024-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
